# Makefile for the EIL Linux client agent steward

include ../Globals.mk


clean:
	@echo Cleaning the build environment
	@rm -f *~ *.o *.so core core.*
	@rm -f logger/*~ logger/*.o logger/*.so logger/core logger/core.*
	@rm -f lib_soap/*~ lib_soap/*.o lib_soap/*.so lib_soap/core lib_soap/core.*
