#!/bin/bash

case $1 in 
build) 
                ./scripts/setup_laf.sh
                ;; 
install) 
                if [ ! -e src/laf-lib.sh.src ]; then  
	         $0 "build"
                fi
                ./scripts/install_laf.sh
                ;; 
clean)
                if [ -e src/laf-lib.sh.src ]; then
                 mv src/laf-lib.sh.src src/laf-lib.sh
                fi
                ;;
*)
                echo "usage: $0 [ build | clean | install ]"
                ;;
esac
