#!/bin/bash

case $1 in 
build) 
                ./scripts/create_relay_sh.sh
                ;; 
install) 
                if [ ! -e src/relay.sh ]; then  
	         $0 "build"
                fi
                ./scripts/install_relay.sh
                ;; 
clean)
                ;;
*)
                echo "usage: $0 [ build | clean | install ]"
                ;;
esac
