/* soapH.h
   Generated by gSOAP 2.7.9l from EILClientOps.h
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

#ifndef SOAP_TYPE__ns3__byte
#define SOAP_TYPE__ns3__byte (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get__ns3__byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in__ns3__byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (2)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE__ns3__short
#define SOAP_TYPE__ns3__short (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__short(struct soap*, short *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__short(struct soap*, const short *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__short(struct soap*, const char*, int, const short *, const char*);
SOAP_FMAC3 short * SOAP_FMAC4 soap_get__ns3__short(struct soap*, short *, const char*, const char*);
SOAP_FMAC3 short * SOAP_FMAC4 soap_in__ns3__short(struct soap*, const char*, short *, const char*);

#ifndef SOAP_TYPE_short
#define SOAP_TYPE_short (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_short(struct soap*, short *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_short(struct soap*, const short *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_short(struct soap*, const char*, int, const short *, const char*);
SOAP_FMAC3 short * SOAP_FMAC4 soap_get_short(struct soap*, short *, const char*, const char*);
SOAP_FMAC3 short * SOAP_FMAC4 soap_in_short(struct soap*, const char*, short *, const char*);

#ifndef SOAP_TYPE__ns3__char
#define SOAP_TYPE__ns3__char (69)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__char(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__char(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__char(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get__ns3__char(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in__ns3__char(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE__ns3__int
#define SOAP_TYPE__ns3__int (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get__ns3__int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in__ns3__int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_ns3__char
#define SOAP_TYPE_ns3__char (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__char(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__char(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__char(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_ns3__char(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_ns3__char(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE__ns3__long
#define SOAP_TYPE__ns3__long (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__long(struct soap*, LONG64 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__long(struct soap*, const LONG64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__long(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get__ns3__long(struct soap*, LONG64 *, const char*, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in__ns3__long(struct soap*, const char*, LONG64 *, const char*);

#ifndef SOAP_TYPE_LONG64
#define SOAP_TYPE_LONG64 (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_LONG64(struct soap*, LONG64 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_LONG64(struct soap*, const LONG64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_LONG64(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get_LONG64(struct soap*, LONG64 *, const char*, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in_LONG64(struct soap*, const char*, LONG64 *, const char*);

#ifndef SOAP_TYPE__ns3__float
#define SOAP_TYPE__ns3__float (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__float(struct soap*, float *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__float(struct soap*, const float *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__float(struct soap*, const char*, int, const float *, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_get__ns3__float(struct soap*, float *, const char*, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_in__ns3__float(struct soap*, const char*, float *, const char*);

#ifndef SOAP_TYPE_float
#define SOAP_TYPE_float (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_float(struct soap*, float *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_float(struct soap*, const float *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_float(struct soap*, const char*, int, const float *, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_get_float(struct soap*, float *, const char*, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_in_float(struct soap*, const char*, float *, const char*);

#ifndef SOAP_TYPE__ns3__double
#define SOAP_TYPE__ns3__double (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__double(struct soap*, double *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__double(struct soap*, const double *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__double(struct soap*, const char*, int, const double *, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_get__ns3__double(struct soap*, double *, const char*, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_in__ns3__double(struct soap*, const char*, double *, const char*);

#ifndef SOAP_TYPE_double
#define SOAP_TYPE_double (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_double(struct soap*, double *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_double(struct soap*, const double *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_double(struct soap*, const char*, int, const double *, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_get_double(struct soap*, double *, const char*, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_in_double(struct soap*, const char*, double *, const char*);

#ifndef SOAP_TYPE__ns3__unsignedByte
#define SOAP_TYPE__ns3__unsignedByte (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__unsignedByte(struct soap*, unsigned char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__unsignedByte(struct soap*, const unsigned char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__unsignedByte(struct soap*, const char*, int, const unsigned char *, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_get__ns3__unsignedByte(struct soap*, unsigned char *, const char*, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_in__ns3__unsignedByte(struct soap*, const char*, unsigned char *, const char*);

#ifndef SOAP_TYPE_unsignedByte
#define SOAP_TYPE_unsignedByte (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedByte(struct soap*, unsigned char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedByte(struct soap*, const unsigned char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedByte(struct soap*, const char*, int, const unsigned char *, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_get_unsignedByte(struct soap*, unsigned char *, const char*, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_in_unsignedByte(struct soap*, const char*, unsigned char *, const char*);

#ifndef SOAP_TYPE__ns3__unsignedShort
#define SOAP_TYPE__ns3__unsignedShort (68)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__unsignedShort(struct soap*, unsigned short *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__unsignedShort(struct soap*, const unsigned short *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__unsignedShort(struct soap*, const char*, int, const unsigned short *, const char*);
SOAP_FMAC3 unsigned short * SOAP_FMAC4 soap_get__ns3__unsignedShort(struct soap*, unsigned short *, const char*, const char*);
SOAP_FMAC3 unsigned short * SOAP_FMAC4 soap_in__ns3__unsignedShort(struct soap*, const char*, unsigned short *, const char*);

#ifndef SOAP_TYPE_unsignedShort
#define SOAP_TYPE_unsignedShort (67)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedShort(struct soap*, unsigned short *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedShort(struct soap*, const unsigned short *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedShort(struct soap*, const char*, int, const unsigned short *, const char*);
SOAP_FMAC3 unsigned short * SOAP_FMAC4 soap_get_unsignedShort(struct soap*, unsigned short *, const char*, const char*);
SOAP_FMAC3 unsigned short * SOAP_FMAC4 soap_in_unsignedShort(struct soap*, const char*, unsigned short *, const char*);

#ifndef SOAP_TYPE__ns3__unsignedInt
#define SOAP_TYPE__ns3__unsignedInt (64)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__unsignedInt(struct soap*, unsigned int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__unsignedInt(struct soap*, const unsigned int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get__ns3__unsignedInt(struct soap*, unsigned int *, const char*, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in__ns3__unsignedInt(struct soap*, const char*, unsigned int *, const char*);

#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedInt(struct soap*, unsigned int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedInt(struct soap*, const unsigned int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get_unsignedInt(struct soap*, unsigned int *, const char*, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in_unsignedInt(struct soap*, const char*, unsigned int *, const char*);

#ifndef SOAP_TYPE__ns3__unsignedLong
#define SOAP_TYPE__ns3__unsignedLong (66)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__unsignedLong(struct soap*, ULONG64 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__unsignedLong(struct soap*, const ULONG64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__unsignedLong(struct soap*, const char*, int, const ULONG64 *, const char*);
SOAP_FMAC3 ULONG64 * SOAP_FMAC4 soap_get__ns3__unsignedLong(struct soap*, ULONG64 *, const char*, const char*);
SOAP_FMAC3 ULONG64 * SOAP_FMAC4 soap_in__ns3__unsignedLong(struct soap*, const char*, ULONG64 *, const char*);

#ifndef SOAP_TYPE_unsignedLONG64
#define SOAP_TYPE_unsignedLONG64 (65)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedLONG64(struct soap*, ULONG64 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedLONG64(struct soap*, const ULONG64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedLONG64(struct soap*, const char*, int, const ULONG64 *, const char*);
SOAP_FMAC3 ULONG64 * SOAP_FMAC4 soap_get_unsignedLONG64(struct soap*, ULONG64 *, const char*, const char*);
SOAP_FMAC3 ULONG64 * SOAP_FMAC4 soap_in_unsignedLONG64(struct soap*, const char*, ULONG64 *, const char*);

#ifndef SOAP_TYPE__ns3__dateTime
#define SOAP_TYPE__ns3__dateTime (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__dateTime(struct soap*, time_t *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__dateTime(struct soap*, const time_t *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__dateTime(struct soap*, const char*, int, const time_t *, const char*);
SOAP_FMAC3 time_t * SOAP_FMAC4 soap_get__ns3__dateTime(struct soap*, time_t *, const char*, const char*);
SOAP_FMAC3 time_t * SOAP_FMAC4 soap_in__ns3__dateTime(struct soap*, const char*, time_t *, const char*);

#ifndef SOAP_TYPE_time
#define SOAP_TYPE_time (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_time(struct soap*, time_t *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_time(struct soap*, const time_t *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_time(struct soap*, const char*, int, const time_t *, const char*);
SOAP_FMAC3 time_t * SOAP_FMAC4 soap_get_time(struct soap*, time_t *, const char*, const char*);
SOAP_FMAC3 time_t * SOAP_FMAC4 soap_in_time(struct soap*, const char*, time_t *, const char*);

#ifndef SOAP_TYPE__ns4__EILCommandStatus
#define SOAP_TYPE__ns4__EILCommandStatus (78)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns4__EILCommandStatus(struct soap*, enum ns4__EILCommandStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns4__EILCommandStatus(struct soap*, const enum ns4__EILCommandStatus *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns4__EILCommandStatus(struct soap*, const char*, int, const enum ns4__EILCommandStatus *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap__ns4__EILCommandStatus2s(struct soap*, enum ns4__EILCommandStatus);
SOAP_FMAC3 enum ns4__EILCommandStatus * SOAP_FMAC4 soap_get__ns4__EILCommandStatus(struct soap*, enum ns4__EILCommandStatus *, const char*, const char*);
SOAP_FMAC3 enum ns4__EILCommandStatus * SOAP_FMAC4 soap_in__ns4__EILCommandStatus(struct soap*, const char*, enum ns4__EILCommandStatus *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2_ns4__EILCommandStatus(struct soap*, const char*, enum ns4__EILCommandStatus *);

#ifndef SOAP_TYPE__ns4__MachineType
#define SOAP_TYPE__ns4__MachineType (76)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns4__MachineType(struct soap*, enum ns4__MachineType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns4__MachineType(struct soap*, const enum ns4__MachineType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns4__MachineType(struct soap*, const char*, int, const enum ns4__MachineType *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap__ns4__MachineType2s(struct soap*, enum ns4__MachineType);
SOAP_FMAC3 enum ns4__MachineType * SOAP_FMAC4 soap_get__ns4__MachineType(struct soap*, enum ns4__MachineType *, const char*, const char*);
SOAP_FMAC3 enum ns4__MachineType * SOAP_FMAC4 soap_in__ns4__MachineType(struct soap*, const char*, enum ns4__MachineType *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2_ns4__MachineType(struct soap*, const char*, enum ns4__MachineType *);

#ifndef SOAP_TYPE__ns3__boolean
#define SOAP_TYPE__ns3__boolean (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__boolean(struct soap*, enum xsd__boolean *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__boolean(struct soap*, const enum xsd__boolean *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__boolean(struct soap*, const char*, int, const enum xsd__boolean *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap__ns3__boolean2s(struct soap*, enum xsd__boolean);
SOAP_FMAC3 enum xsd__boolean * SOAP_FMAC4 soap_get__ns3__boolean(struct soap*, enum xsd__boolean *, const char*, const char*);
SOAP_FMAC3 enum xsd__boolean * SOAP_FMAC4 soap_in__ns3__boolean(struct soap*, const char*, enum xsd__boolean *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2_ns3__boolean(struct soap*, const char*, enum xsd__boolean *);

#ifndef SOAP_TYPE_ns4__EILCommandStatus
#define SOAP_TYPE_ns4__EILCommandStatus (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns4__EILCommandStatus(struct soap*, enum ns4__EILCommandStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns4__EILCommandStatus(struct soap*, const enum ns4__EILCommandStatus *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns4__EILCommandStatus(struct soap*, const char*, int, const enum ns4__EILCommandStatus *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_ns4__EILCommandStatus2s(struct soap*, enum ns4__EILCommandStatus);
SOAP_FMAC3 enum ns4__EILCommandStatus * SOAP_FMAC4 soap_get_ns4__EILCommandStatus(struct soap*, enum ns4__EILCommandStatus *, const char*, const char*);
SOAP_FMAC3 enum ns4__EILCommandStatus * SOAP_FMAC4 soap_in_ns4__EILCommandStatus(struct soap*, const char*, enum ns4__EILCommandStatus *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2ns4__EILCommandStatus(struct soap*, const char*, enum ns4__EILCommandStatus *);

#ifndef SOAP_TYPE_ns4__MachineType
#define SOAP_TYPE_ns4__MachineType (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns4__MachineType(struct soap*, enum ns4__MachineType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns4__MachineType(struct soap*, const enum ns4__MachineType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns4__MachineType(struct soap*, const char*, int, const enum ns4__MachineType *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_ns4__MachineType2s(struct soap*, enum ns4__MachineType);
SOAP_FMAC3 enum ns4__MachineType * SOAP_FMAC4 soap_get_ns4__MachineType(struct soap*, enum ns4__MachineType *, const char*, const char*);
SOAP_FMAC3 enum ns4__MachineType * SOAP_FMAC4 soap_in_ns4__MachineType(struct soap*, const char*, enum ns4__MachineType *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2ns4__MachineType(struct soap*, const char*, enum ns4__MachineType *);

#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__boolean(struct soap*, enum xsd__boolean *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__boolean(struct soap*, const enum xsd__boolean *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__boolean(struct soap*, const char*, int, const enum xsd__boolean *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_xsd__boolean2s(struct soap*, enum xsd__boolean);
SOAP_FMAC3 enum xsd__boolean * SOAP_FMAC4 soap_get_xsd__boolean(struct soap*, enum xsd__boolean *, const char*, const char*);
SOAP_FMAC3 enum xsd__boolean * SOAP_FMAC4 soap_in_xsd__boolean(struct soap*, const char*, enum xsd__boolean *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2xsd__boolean(struct soap*, const char*, enum xsd__boolean *);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (104)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (103)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (100)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (98)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (97)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#endif

#ifndef SOAP_TYPE___ns1__InitiateClientCommands
#define SOAP_TYPE___ns1__InitiateClientCommands (96)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__InitiateClientCommands(struct soap*, struct __ns1__InitiateClientCommands *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__InitiateClientCommands(struct soap*, const struct __ns1__InitiateClientCommands *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__InitiateClientCommands(struct soap*, const struct __ns1__InitiateClientCommands *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__InitiateClientCommands(struct soap*, const char*, int, const struct __ns1__InitiateClientCommands *, const char*);
SOAP_FMAC3 struct __ns1__InitiateClientCommands * SOAP_FMAC4 soap_get___ns1__InitiateClientCommands(struct soap*, struct __ns1__InitiateClientCommands *, const char*, const char*);
SOAP_FMAC3 struct __ns1__InitiateClientCommands * SOAP_FMAC4 soap_in___ns1__InitiateClientCommands(struct soap*, const char*, struct __ns1__InitiateClientCommands *, const char*);

#ifndef SOAP_TYPE___ns1__GetCommandStatus
#define SOAP_TYPE___ns1__GetCommandStatus (92)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__GetCommandStatus(struct soap*, struct __ns1__GetCommandStatus *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__GetCommandStatus(struct soap*, const struct __ns1__GetCommandStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__GetCommandStatus(struct soap*, const struct __ns1__GetCommandStatus *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__GetCommandStatus(struct soap*, const char*, int, const struct __ns1__GetCommandStatus *, const char*);
SOAP_FMAC3 struct __ns1__GetCommandStatus * SOAP_FMAC4 soap_get___ns1__GetCommandStatus(struct soap*, struct __ns1__GetCommandStatus *, const char*, const char*);
SOAP_FMAC3 struct __ns1__GetCommandStatus * SOAP_FMAC4 soap_in___ns1__GetCommandStatus(struct soap*, const char*, struct __ns1__GetCommandStatus *, const char*);

#ifndef SOAP_TYPE___ns1__UpdateCommandStatus
#define SOAP_TYPE___ns1__UpdateCommandStatus (88)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__UpdateCommandStatus(struct soap*, struct __ns1__UpdateCommandStatus *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__UpdateCommandStatus(struct soap*, const struct __ns1__UpdateCommandStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__UpdateCommandStatus(struct soap*, const struct __ns1__UpdateCommandStatus *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__UpdateCommandStatus(struct soap*, const char*, int, const struct __ns1__UpdateCommandStatus *, const char*);
SOAP_FMAC3 struct __ns1__UpdateCommandStatus * SOAP_FMAC4 soap_get___ns1__UpdateCommandStatus(struct soap*, struct __ns1__UpdateCommandStatus *, const char*, const char*);
SOAP_FMAC3 struct __ns1__UpdateCommandStatus * SOAP_FMAC4 soap_in___ns1__UpdateCommandStatus(struct soap*, const char*, struct __ns1__UpdateCommandStatus *, const char*);

#ifndef SOAP_TYPE___ns1__GetCommandToExecute
#define SOAP_TYPE___ns1__GetCommandToExecute (84)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__GetCommandToExecute(struct soap*, struct __ns1__GetCommandToExecute *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__GetCommandToExecute(struct soap*, const struct __ns1__GetCommandToExecute *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__GetCommandToExecute(struct soap*, const struct __ns1__GetCommandToExecute *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__GetCommandToExecute(struct soap*, const char*, int, const struct __ns1__GetCommandToExecute *, const char*);
SOAP_FMAC3 struct __ns1__GetCommandToExecute * SOAP_FMAC4 soap_get___ns1__GetCommandToExecute(struct soap*, struct __ns1__GetCommandToExecute *, const char*, const char*);
SOAP_FMAC3 struct __ns1__GetCommandToExecute * SOAP_FMAC4 soap_in___ns1__GetCommandToExecute(struct soap*, const char*, struct __ns1__GetCommandToExecute *, const char*);

#ifndef SOAP_TYPE__ns5__ArrayOfKeyValueOfstringstring
#define SOAP_TYPE__ns5__ArrayOfKeyValueOfstringstring (80)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns5__ArrayOfKeyValueOfstringstring(struct soap*, struct ns5__ArrayOfKeyValueOfstringstring *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns5__ArrayOfKeyValueOfstringstring(struct soap*, struct ns5__ArrayOfKeyValueOfstringstring const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns5__ArrayOfKeyValueOfstringstring(struct soap*, const struct ns5__ArrayOfKeyValueOfstringstring *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns5__ArrayOfKeyValueOfstringstring(struct soap*, const char*, int, const struct ns5__ArrayOfKeyValueOfstringstring *, const char*);
SOAP_FMAC3 struct ns5__ArrayOfKeyValueOfstringstring * SOAP_FMAC4 soap_get__ns5__ArrayOfKeyValueOfstringstring(struct soap*, struct ns5__ArrayOfKeyValueOfstringstring *, const char*, const char*);
SOAP_FMAC3 struct ns5__ArrayOfKeyValueOfstringstring * SOAP_FMAC4 soap_in__ns5__ArrayOfKeyValueOfstringstring(struct soap*, const char*, struct ns5__ArrayOfKeyValueOfstringstring *, const char*);

#ifndef SOAP_TYPE__ns5__ArrayOfstring
#define SOAP_TYPE__ns5__ArrayOfstring (79)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns5__ArrayOfstring(struct soap*, struct ns5__ArrayOfstring *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns5__ArrayOfstring(struct soap*, struct ns5__ArrayOfstring const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns5__ArrayOfstring(struct soap*, const struct ns5__ArrayOfstring *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns5__ArrayOfstring(struct soap*, const char*, int, const struct ns5__ArrayOfstring *, const char*);
SOAP_FMAC3 struct ns5__ArrayOfstring * SOAP_FMAC4 soap_get__ns5__ArrayOfstring(struct soap*, struct ns5__ArrayOfstring *, const char*, const char*);
SOAP_FMAC3 struct ns5__ArrayOfstring * SOAP_FMAC4 soap_in__ns5__ArrayOfstring(struct soap*, const char*, struct ns5__ArrayOfstring *, const char*);

#ifndef SOAP_TYPE__ns4__EILCommand
#define SOAP_TYPE__ns4__EILCommand (77)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns4__EILCommand(struct soap*, struct ns4__EILCommand *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns4__EILCommand(struct soap*, struct ns4__EILCommand const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns4__EILCommand(struct soap*, const struct ns4__EILCommand *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns4__EILCommand(struct soap*, const char*, int, const struct ns4__EILCommand *, const char*);
SOAP_FMAC3 struct ns4__EILCommand * SOAP_FMAC4 soap_get__ns4__EILCommand(struct soap*, struct ns4__EILCommand *, const char*, const char*);
SOAP_FMAC3 struct ns4__EILCommand * SOAP_FMAC4 soap_in__ns4__EILCommand(struct soap*, const char*, struct ns4__EILCommand *, const char*);

#ifndef SOAP_TYPE__ns4__MachineContext
#define SOAP_TYPE__ns4__MachineContext (75)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns4__MachineContext(struct soap*, struct ns4__MachineContext *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns4__MachineContext(struct soap*, struct ns4__MachineContext const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns4__MachineContext(struct soap*, const struct ns4__MachineContext *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns4__MachineContext(struct soap*, const char*, int, const struct ns4__MachineContext *, const char*);
SOAP_FMAC3 struct ns4__MachineContext * SOAP_FMAC4 soap_get__ns4__MachineContext(struct soap*, struct ns4__MachineContext *, const char*, const char*);
SOAP_FMAC3 struct ns4__MachineContext * SOAP_FMAC4 soap_in__ns4__MachineContext(struct soap*, const char*, struct ns4__MachineContext *, const char*);

#ifndef SOAP_TYPE__ns3__base64Binary
#define SOAP_TYPE__ns3__base64Binary (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__base64Binary(struct soap*, struct xsd__base64Binary *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns3__base64Binary(struct soap*, struct xsd__base64Binary const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__base64Binary(struct soap*, const struct xsd__base64Binary *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__base64Binary(struct soap*, const char*, int, const struct xsd__base64Binary *, const char*);
SOAP_FMAC3 struct xsd__base64Binary * SOAP_FMAC4 soap_get__ns3__base64Binary(struct soap*, struct xsd__base64Binary *, const char*, const char*);
SOAP_FMAC3 struct xsd__base64Binary * SOAP_FMAC4 soap_in__ns3__base64Binary(struct soap*, const char*, struct xsd__base64Binary *, const char*);

#ifndef SOAP_TYPE__ns5__ArrayOfKeyValueOfstringstring_KeyValueOfstringstring
#define SOAP_TYPE__ns5__ArrayOfKeyValueOfstringstring_KeyValueOfstringstring (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns5__ArrayOfKeyValueOfstringstring_KeyValueOfstringstring(struct soap*, struct _ns5__ArrayOfKeyValueOfstringstring_KeyValueOfstringstring *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns5__ArrayOfKeyValueOfstringstring_KeyValueOfstringstring(struct soap*, const struct _ns5__ArrayOfKeyValueOfstringstring_KeyValueOfstringstring *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns5__ArrayOfKeyValueOfstringstring_KeyValueOfstringstring(struct soap*, const struct _ns5__ArrayOfKeyValueOfstringstring_KeyValueOfstringstring *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns5__ArrayOfKeyValueOfstringstring_KeyValueOfstringstring(struct soap*, const char*, int, const struct _ns5__ArrayOfKeyValueOfstringstring_KeyValueOfstringstring *, const char*);
SOAP_FMAC3 struct _ns5__ArrayOfKeyValueOfstringstring_KeyValueOfstringstring * SOAP_FMAC4 soap_get__ns5__ArrayOfKeyValueOfstringstring_KeyValueOfstringstring(struct soap*, struct _ns5__ArrayOfKeyValueOfstringstring_KeyValueOfstringstring *, const char*, const char*);
SOAP_FMAC3 struct _ns5__ArrayOfKeyValueOfstringstring_KeyValueOfstringstring * SOAP_FMAC4 soap_in__ns5__ArrayOfKeyValueOfstringstring_KeyValueOfstringstring(struct soap*, const char*, struct _ns5__ArrayOfKeyValueOfstringstring_KeyValueOfstringstring *, const char*);

#ifndef SOAP_TYPE_ns5__ArrayOfKeyValueOfstringstring
#define SOAP_TYPE_ns5__ArrayOfKeyValueOfstringstring (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns5__ArrayOfKeyValueOfstringstring(struct soap*, struct ns5__ArrayOfKeyValueOfstringstring *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns5__ArrayOfKeyValueOfstringstring(struct soap*, const struct ns5__ArrayOfKeyValueOfstringstring *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns5__ArrayOfKeyValueOfstringstring(struct soap*, const struct ns5__ArrayOfKeyValueOfstringstring *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns5__ArrayOfKeyValueOfstringstring(struct soap*, const char*, int, const struct ns5__ArrayOfKeyValueOfstringstring *, const char*);
SOAP_FMAC3 struct ns5__ArrayOfKeyValueOfstringstring * SOAP_FMAC4 soap_get_ns5__ArrayOfKeyValueOfstringstring(struct soap*, struct ns5__ArrayOfKeyValueOfstringstring *, const char*, const char*);
SOAP_FMAC3 struct ns5__ArrayOfKeyValueOfstringstring * SOAP_FMAC4 soap_in_ns5__ArrayOfKeyValueOfstringstring(struct soap*, const char*, struct ns5__ArrayOfKeyValueOfstringstring *, const char*);

#ifndef SOAP_TYPE_ns5__ArrayOfstring
#define SOAP_TYPE_ns5__ArrayOfstring (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns5__ArrayOfstring(struct soap*, struct ns5__ArrayOfstring *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns5__ArrayOfstring(struct soap*, const struct ns5__ArrayOfstring *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns5__ArrayOfstring(struct soap*, const struct ns5__ArrayOfstring *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns5__ArrayOfstring(struct soap*, const char*, int, const struct ns5__ArrayOfstring *, const char*);
SOAP_FMAC3 struct ns5__ArrayOfstring * SOAP_FMAC4 soap_get_ns5__ArrayOfstring(struct soap*, struct ns5__ArrayOfstring *, const char*, const char*);
SOAP_FMAC3 struct ns5__ArrayOfstring * SOAP_FMAC4 soap_in_ns5__ArrayOfstring(struct soap*, const char*, struct ns5__ArrayOfstring *, const char*);

#ifndef SOAP_TYPE__ns1__InitiateClientCommandsResponse
#define SOAP_TYPE__ns1__InitiateClientCommandsResponse (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__InitiateClientCommandsResponse(struct soap*, struct _ns1__InitiateClientCommandsResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__InitiateClientCommandsResponse(struct soap*, const struct _ns1__InitiateClientCommandsResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__InitiateClientCommandsResponse(struct soap*, const struct _ns1__InitiateClientCommandsResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__InitiateClientCommandsResponse(struct soap*, const char*, int, const struct _ns1__InitiateClientCommandsResponse *, const char*);
SOAP_FMAC3 struct _ns1__InitiateClientCommandsResponse * SOAP_FMAC4 soap_get__ns1__InitiateClientCommandsResponse(struct soap*, struct _ns1__InitiateClientCommandsResponse *, const char*, const char*);
SOAP_FMAC3 struct _ns1__InitiateClientCommandsResponse * SOAP_FMAC4 soap_in__ns1__InitiateClientCommandsResponse(struct soap*, const char*, struct _ns1__InitiateClientCommandsResponse *, const char*);

#ifndef SOAP_TYPE__ns1__InitiateClientCommands
#define SOAP_TYPE__ns1__InitiateClientCommands (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__InitiateClientCommands(struct soap*, struct _ns1__InitiateClientCommands *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__InitiateClientCommands(struct soap*, const struct _ns1__InitiateClientCommands *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__InitiateClientCommands(struct soap*, const struct _ns1__InitiateClientCommands *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__InitiateClientCommands(struct soap*, const char*, int, const struct _ns1__InitiateClientCommands *, const char*);
SOAP_FMAC3 struct _ns1__InitiateClientCommands * SOAP_FMAC4 soap_get__ns1__InitiateClientCommands(struct soap*, struct _ns1__InitiateClientCommands *, const char*, const char*);
SOAP_FMAC3 struct _ns1__InitiateClientCommands * SOAP_FMAC4 soap_in__ns1__InitiateClientCommands(struct soap*, const char*, struct _ns1__InitiateClientCommands *, const char*);

#ifndef SOAP_TYPE__ns1__GetCommandStatusResponse
#define SOAP_TYPE__ns1__GetCommandStatusResponse (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__GetCommandStatusResponse(struct soap*, struct _ns1__GetCommandStatusResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__GetCommandStatusResponse(struct soap*, const struct _ns1__GetCommandStatusResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__GetCommandStatusResponse(struct soap*, const struct _ns1__GetCommandStatusResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetCommandStatusResponse(struct soap*, const char*, int, const struct _ns1__GetCommandStatusResponse *, const char*);
SOAP_FMAC3 struct _ns1__GetCommandStatusResponse * SOAP_FMAC4 soap_get__ns1__GetCommandStatusResponse(struct soap*, struct _ns1__GetCommandStatusResponse *, const char*, const char*);
SOAP_FMAC3 struct _ns1__GetCommandStatusResponse * SOAP_FMAC4 soap_in__ns1__GetCommandStatusResponse(struct soap*, const char*, struct _ns1__GetCommandStatusResponse *, const char*);

#ifndef SOAP_TYPE__ns1__GetCommandStatus
#define SOAP_TYPE__ns1__GetCommandStatus (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__GetCommandStatus(struct soap*, struct _ns1__GetCommandStatus *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__GetCommandStatus(struct soap*, const struct _ns1__GetCommandStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__GetCommandStatus(struct soap*, const struct _ns1__GetCommandStatus *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetCommandStatus(struct soap*, const char*, int, const struct _ns1__GetCommandStatus *, const char*);
SOAP_FMAC3 struct _ns1__GetCommandStatus * SOAP_FMAC4 soap_get__ns1__GetCommandStatus(struct soap*, struct _ns1__GetCommandStatus *, const char*, const char*);
SOAP_FMAC3 struct _ns1__GetCommandStatus * SOAP_FMAC4 soap_in__ns1__GetCommandStatus(struct soap*, const char*, struct _ns1__GetCommandStatus *, const char*);

#ifndef SOAP_TYPE__ns1__UpdateCommandStatusResponse
#define SOAP_TYPE__ns1__UpdateCommandStatusResponse (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__UpdateCommandStatusResponse(struct soap*, struct _ns1__UpdateCommandStatusResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__UpdateCommandStatusResponse(struct soap*, const struct _ns1__UpdateCommandStatusResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__UpdateCommandStatusResponse(struct soap*, const struct _ns1__UpdateCommandStatusResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__UpdateCommandStatusResponse(struct soap*, const char*, int, const struct _ns1__UpdateCommandStatusResponse *, const char*);
SOAP_FMAC3 struct _ns1__UpdateCommandStatusResponse * SOAP_FMAC4 soap_get__ns1__UpdateCommandStatusResponse(struct soap*, struct _ns1__UpdateCommandStatusResponse *, const char*, const char*);
SOAP_FMAC3 struct _ns1__UpdateCommandStatusResponse * SOAP_FMAC4 soap_in__ns1__UpdateCommandStatusResponse(struct soap*, const char*, struct _ns1__UpdateCommandStatusResponse *, const char*);

#ifndef SOAP_TYPE__ns1__UpdateCommandStatus
#define SOAP_TYPE__ns1__UpdateCommandStatus (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__UpdateCommandStatus(struct soap*, struct _ns1__UpdateCommandStatus *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__UpdateCommandStatus(struct soap*, const struct _ns1__UpdateCommandStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__UpdateCommandStatus(struct soap*, const struct _ns1__UpdateCommandStatus *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__UpdateCommandStatus(struct soap*, const char*, int, const struct _ns1__UpdateCommandStatus *, const char*);
SOAP_FMAC3 struct _ns1__UpdateCommandStatus * SOAP_FMAC4 soap_get__ns1__UpdateCommandStatus(struct soap*, struct _ns1__UpdateCommandStatus *, const char*, const char*);
SOAP_FMAC3 struct _ns1__UpdateCommandStatus * SOAP_FMAC4 soap_in__ns1__UpdateCommandStatus(struct soap*, const char*, struct _ns1__UpdateCommandStatus *, const char*);

#ifndef SOAP_TYPE_ns4__EILCommand
#define SOAP_TYPE_ns4__EILCommand (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns4__EILCommand(struct soap*, struct ns4__EILCommand *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns4__EILCommand(struct soap*, const struct ns4__EILCommand *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns4__EILCommand(struct soap*, const struct ns4__EILCommand *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns4__EILCommand(struct soap*, const char*, int, const struct ns4__EILCommand *, const char*);
SOAP_FMAC3 struct ns4__EILCommand * SOAP_FMAC4 soap_get_ns4__EILCommand(struct soap*, struct ns4__EILCommand *, const char*, const char*);
SOAP_FMAC3 struct ns4__EILCommand * SOAP_FMAC4 soap_in_ns4__EILCommand(struct soap*, const char*, struct ns4__EILCommand *, const char*);

#ifndef SOAP_TYPE__ns1__GetCommandToExecuteResponse
#define SOAP_TYPE__ns1__GetCommandToExecuteResponse (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__GetCommandToExecuteResponse(struct soap*, struct _ns1__GetCommandToExecuteResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__GetCommandToExecuteResponse(struct soap*, const struct _ns1__GetCommandToExecuteResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__GetCommandToExecuteResponse(struct soap*, const struct _ns1__GetCommandToExecuteResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetCommandToExecuteResponse(struct soap*, const char*, int, const struct _ns1__GetCommandToExecuteResponse *, const char*);
SOAP_FMAC3 struct _ns1__GetCommandToExecuteResponse * SOAP_FMAC4 soap_get__ns1__GetCommandToExecuteResponse(struct soap*, struct _ns1__GetCommandToExecuteResponse *, const char*, const char*);
SOAP_FMAC3 struct _ns1__GetCommandToExecuteResponse * SOAP_FMAC4 soap_in__ns1__GetCommandToExecuteResponse(struct soap*, const char*, struct _ns1__GetCommandToExecuteResponse *, const char*);

#ifndef SOAP_TYPE_ns4__MachineContext
#define SOAP_TYPE_ns4__MachineContext (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns4__MachineContext(struct soap*, struct ns4__MachineContext *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns4__MachineContext(struct soap*, const struct ns4__MachineContext *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns4__MachineContext(struct soap*, const struct ns4__MachineContext *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns4__MachineContext(struct soap*, const char*, int, const struct ns4__MachineContext *, const char*);
SOAP_FMAC3 struct ns4__MachineContext * SOAP_FMAC4 soap_get_ns4__MachineContext(struct soap*, struct ns4__MachineContext *, const char*, const char*);
SOAP_FMAC3 struct ns4__MachineContext * SOAP_FMAC4 soap_in_ns4__MachineContext(struct soap*, const char*, struct ns4__MachineContext *, const char*);

#ifndef SOAP_TYPE__ns1__GetCommandToExecute
#define SOAP_TYPE__ns1__GetCommandToExecute (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__GetCommandToExecute(struct soap*, struct _ns1__GetCommandToExecute *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__GetCommandToExecute(struct soap*, const struct _ns1__GetCommandToExecute *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__GetCommandToExecute(struct soap*, const struct _ns1__GetCommandToExecute *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetCommandToExecute(struct soap*, const char*, int, const struct _ns1__GetCommandToExecute *, const char*);
SOAP_FMAC3 struct _ns1__GetCommandToExecute * SOAP_FMAC4 soap_get__ns1__GetCommandToExecute(struct soap*, struct _ns1__GetCommandToExecute *, const char*, const char*);
SOAP_FMAC3 struct _ns1__GetCommandToExecute * SOAP_FMAC4 soap_in__ns1__GetCommandToExecute(struct soap*, const char*, struct _ns1__GetCommandToExecute *, const char*);

#ifndef SOAP_TYPE_xsd__base64Binary
#define SOAP_TYPE_xsd__base64Binary (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__base64Binary(struct soap*, struct xsd__base64Binary *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__base64Binary(struct soap*, struct xsd__base64Binary const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__base64Binary(struct soap*, const struct xsd__base64Binary *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__base64Binary(struct soap*, const char*, int, const struct xsd__base64Binary *, const char*);
SOAP_FMAC3 struct xsd__base64Binary * SOAP_FMAC4 soap_get_xsd__base64Binary(struct soap*, struct xsd__base64Binary *, const char*, const char*);
SOAP_FMAC3 struct xsd__base64Binary * SOAP_FMAC4 soap_in_xsd__base64Binary(struct soap*, const char*, struct xsd__base64Binary *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (106)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (105)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (99)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTo_ns1__InitiateClientCommandsResponse
#define SOAP_TYPE_PointerTo_ns1__InitiateClientCommandsResponse (94)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__InitiateClientCommandsResponse(struct soap*, struct _ns1__InitiateClientCommandsResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__InitiateClientCommandsResponse(struct soap*, struct _ns1__InitiateClientCommandsResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__InitiateClientCommandsResponse(struct soap*, const char *, int, struct _ns1__InitiateClientCommandsResponse *const*, const char *);
SOAP_FMAC3 struct _ns1__InitiateClientCommandsResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__InitiateClientCommandsResponse(struct soap*, struct _ns1__InitiateClientCommandsResponse **, const char*, const char*);
SOAP_FMAC3 struct _ns1__InitiateClientCommandsResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__InitiateClientCommandsResponse(struct soap*, const char*, struct _ns1__InitiateClientCommandsResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__InitiateClientCommands
#define SOAP_TYPE_PointerTo_ns1__InitiateClientCommands (93)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__InitiateClientCommands(struct soap*, struct _ns1__InitiateClientCommands *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__InitiateClientCommands(struct soap*, struct _ns1__InitiateClientCommands *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__InitiateClientCommands(struct soap*, const char *, int, struct _ns1__InitiateClientCommands *const*, const char *);
SOAP_FMAC3 struct _ns1__InitiateClientCommands ** SOAP_FMAC4 soap_get_PointerTo_ns1__InitiateClientCommands(struct soap*, struct _ns1__InitiateClientCommands **, const char*, const char*);
SOAP_FMAC3 struct _ns1__InitiateClientCommands ** SOAP_FMAC4 soap_in_PointerTo_ns1__InitiateClientCommands(struct soap*, const char*, struct _ns1__InitiateClientCommands **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetCommandStatusResponse
#define SOAP_TYPE_PointerTo_ns1__GetCommandStatusResponse (90)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetCommandStatusResponse(struct soap*, struct _ns1__GetCommandStatusResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetCommandStatusResponse(struct soap*, struct _ns1__GetCommandStatusResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetCommandStatusResponse(struct soap*, const char *, int, struct _ns1__GetCommandStatusResponse *const*, const char *);
SOAP_FMAC3 struct _ns1__GetCommandStatusResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetCommandStatusResponse(struct soap*, struct _ns1__GetCommandStatusResponse **, const char*, const char*);
SOAP_FMAC3 struct _ns1__GetCommandStatusResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetCommandStatusResponse(struct soap*, const char*, struct _ns1__GetCommandStatusResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetCommandStatus
#define SOAP_TYPE_PointerTo_ns1__GetCommandStatus (89)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetCommandStatus(struct soap*, struct _ns1__GetCommandStatus *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetCommandStatus(struct soap*, struct _ns1__GetCommandStatus *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetCommandStatus(struct soap*, const char *, int, struct _ns1__GetCommandStatus *const*, const char *);
SOAP_FMAC3 struct _ns1__GetCommandStatus ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetCommandStatus(struct soap*, struct _ns1__GetCommandStatus **, const char*, const char*);
SOAP_FMAC3 struct _ns1__GetCommandStatus ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetCommandStatus(struct soap*, const char*, struct _ns1__GetCommandStatus **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__UpdateCommandStatusResponse
#define SOAP_TYPE_PointerTo_ns1__UpdateCommandStatusResponse (86)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__UpdateCommandStatusResponse(struct soap*, struct _ns1__UpdateCommandStatusResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__UpdateCommandStatusResponse(struct soap*, struct _ns1__UpdateCommandStatusResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__UpdateCommandStatusResponse(struct soap*, const char *, int, struct _ns1__UpdateCommandStatusResponse *const*, const char *);
SOAP_FMAC3 struct _ns1__UpdateCommandStatusResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__UpdateCommandStatusResponse(struct soap*, struct _ns1__UpdateCommandStatusResponse **, const char*, const char*);
SOAP_FMAC3 struct _ns1__UpdateCommandStatusResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__UpdateCommandStatusResponse(struct soap*, const char*, struct _ns1__UpdateCommandStatusResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__UpdateCommandStatus
#define SOAP_TYPE_PointerTo_ns1__UpdateCommandStatus (85)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__UpdateCommandStatus(struct soap*, struct _ns1__UpdateCommandStatus *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__UpdateCommandStatus(struct soap*, struct _ns1__UpdateCommandStatus *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__UpdateCommandStatus(struct soap*, const char *, int, struct _ns1__UpdateCommandStatus *const*, const char *);
SOAP_FMAC3 struct _ns1__UpdateCommandStatus ** SOAP_FMAC4 soap_get_PointerTo_ns1__UpdateCommandStatus(struct soap*, struct _ns1__UpdateCommandStatus **, const char*, const char*);
SOAP_FMAC3 struct _ns1__UpdateCommandStatus ** SOAP_FMAC4 soap_in_PointerTo_ns1__UpdateCommandStatus(struct soap*, const char*, struct _ns1__UpdateCommandStatus **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetCommandToExecuteResponse
#define SOAP_TYPE_PointerTo_ns1__GetCommandToExecuteResponse (82)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetCommandToExecuteResponse(struct soap*, struct _ns1__GetCommandToExecuteResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetCommandToExecuteResponse(struct soap*, struct _ns1__GetCommandToExecuteResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetCommandToExecuteResponse(struct soap*, const char *, int, struct _ns1__GetCommandToExecuteResponse *const*, const char *);
SOAP_FMAC3 struct _ns1__GetCommandToExecuteResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetCommandToExecuteResponse(struct soap*, struct _ns1__GetCommandToExecuteResponse **, const char*, const char*);
SOAP_FMAC3 struct _ns1__GetCommandToExecuteResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetCommandToExecuteResponse(struct soap*, const char*, struct _ns1__GetCommandToExecuteResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetCommandToExecute
#define SOAP_TYPE_PointerTo_ns1__GetCommandToExecute (81)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetCommandToExecute(struct soap*, struct _ns1__GetCommandToExecute *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetCommandToExecute(struct soap*, struct _ns1__GetCommandToExecute *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetCommandToExecute(struct soap*, const char *, int, struct _ns1__GetCommandToExecute *const*, const char *);
SOAP_FMAC3 struct _ns1__GetCommandToExecute ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetCommandToExecute(struct soap*, struct _ns1__GetCommandToExecute **, const char*, const char*);
SOAP_FMAC3 struct _ns1__GetCommandToExecute ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetCommandToExecute(struct soap*, const char*, struct _ns1__GetCommandToExecute **, const char*);

#ifndef SOAP_TYPE__ns3__Ref
#define SOAP_TYPE__ns3__Ref (74)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__Ref(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns3__Ref(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__Ref(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__Ref(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__ns3__Ref(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__ns3__Ref(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE__ns3__Id
#define SOAP_TYPE__ns3__Id (73)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__Id(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns3__Id(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__Id(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__Id(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__ns3__Id(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__ns3__Id(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE__ns3__FactoryType
#define SOAP_TYPE__ns3__FactoryType (72)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__FactoryType(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns3__FactoryType(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__FactoryType(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__FactoryType(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__ns3__FactoryType(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__ns3__FactoryType(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE__ns3__guid
#define SOAP_TYPE__ns3__guid (71)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__guid(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns3__guid(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__guid(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__guid(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__ns3__guid(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__ns3__guid(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE__ns3__duration
#define SOAP_TYPE__ns3__duration (70)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__duration(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns3__duration(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__duration(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__duration(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__ns3__duration(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__ns3__duration(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE__ns3__string
#define SOAP_TYPE__ns3__string (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns3__string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__ns3__string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__ns3__string(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE__ns3__QName
#define SOAP_TYPE__ns3__QName (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns3__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__ns3__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__ns3__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE__ns3__decimal
#define SOAP_TYPE__ns3__decimal (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__decimal(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns3__decimal(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__decimal(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__decimal(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__ns3__decimal(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__ns3__decimal(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE__ns3__anyURI
#define SOAP_TYPE__ns3__anyURI (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__anyURI(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns3__anyURI(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__anyURI(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__anyURI(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__ns3__anyURI(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__ns3__anyURI(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE__ns3__anyType
#define SOAP_TYPE__ns3__anyType (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__anyType(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns3__anyType(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__anyType(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__anyType(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__ns3__anyType(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__ns3__anyType(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns5__ArrayOfKeyValueOfstringstring_KeyValueOfstringstring
#define SOAP_TYPE_PointerTo_ns5__ArrayOfKeyValueOfstringstring_KeyValueOfstringstring (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns5__ArrayOfKeyValueOfstringstring_KeyValueOfstringstring(struct soap*, struct _ns5__ArrayOfKeyValueOfstringstring_KeyValueOfstringstring *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns5__ArrayOfKeyValueOfstringstring_KeyValueOfstringstring(struct soap*, struct _ns5__ArrayOfKeyValueOfstringstring_KeyValueOfstringstring *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns5__ArrayOfKeyValueOfstringstring_KeyValueOfstringstring(struct soap*, const char *, int, struct _ns5__ArrayOfKeyValueOfstringstring_KeyValueOfstringstring *const*, const char *);
SOAP_FMAC3 struct _ns5__ArrayOfKeyValueOfstringstring_KeyValueOfstringstring ** SOAP_FMAC4 soap_get_PointerTo_ns5__ArrayOfKeyValueOfstringstring_KeyValueOfstringstring(struct soap*, struct _ns5__ArrayOfKeyValueOfstringstring_KeyValueOfstringstring **, const char*, const char*);
SOAP_FMAC3 struct _ns5__ArrayOfKeyValueOfstringstring_KeyValueOfstringstring ** SOAP_FMAC4 soap_in_PointerTo_ns5__ArrayOfKeyValueOfstringstring_KeyValueOfstringstring(struct soap*, const char*, struct _ns5__ArrayOfKeyValueOfstringstring_KeyValueOfstringstring **, const char*);

#ifndef SOAP_TYPE_PointerTostring
#define SOAP_TYPE_PointerTostring (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostring(struct soap*, char **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostring(struct soap*, char **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostring(struct soap*, const char *, int, char **const*, const char *);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_get_PointerTostring(struct soap*, char ***, const char*, const char*);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_in_PointerTostring(struct soap*, const char*, char ***, const char*);

#ifndef SOAP_TYPE_PointerToint
#define SOAP_TYPE_PointerToint (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToint(struct soap*, int *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToint(struct soap*, int *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToint(struct soap*, const char *, int, int *const*, const char *);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_get_PointerToint(struct soap*, int **, const char*, const char*);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_in_PointerToint(struct soap*, const char*, int **, const char*);

#ifndef SOAP_TYPE_PointerTons4__EILCommandStatus
#define SOAP_TYPE_PointerTons4__EILCommandStatus (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons4__EILCommandStatus(struct soap*, enum ns4__EILCommandStatus *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons4__EILCommandStatus(struct soap*, enum ns4__EILCommandStatus *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons4__EILCommandStatus(struct soap*, const char *, int, enum ns4__EILCommandStatus *const*, const char *);
SOAP_FMAC3 enum ns4__EILCommandStatus ** SOAP_FMAC4 soap_get_PointerTons4__EILCommandStatus(struct soap*, enum ns4__EILCommandStatus **, const char*, const char*);
SOAP_FMAC3 enum ns4__EILCommandStatus ** SOAP_FMAC4 soap_in_PointerTons4__EILCommandStatus(struct soap*, const char*, enum ns4__EILCommandStatus **, const char*);

#ifndef SOAP_TYPE_PointerTons4__MachineType
#define SOAP_TYPE_PointerTons4__MachineType (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons4__MachineType(struct soap*, enum ns4__MachineType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons4__MachineType(struct soap*, enum ns4__MachineType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons4__MachineType(struct soap*, const char *, int, enum ns4__MachineType *const*, const char *);
SOAP_FMAC3 enum ns4__MachineType ** SOAP_FMAC4 soap_get_PointerTons4__MachineType(struct soap*, enum ns4__MachineType **, const char*, const char*);
SOAP_FMAC3 enum ns4__MachineType ** SOAP_FMAC4 soap_in_PointerTons4__MachineType(struct soap*, const char*, enum ns4__MachineType **, const char*);

#ifndef SOAP_TYPE_PointerTons5__ArrayOfKeyValueOfstringstring
#define SOAP_TYPE_PointerTons5__ArrayOfKeyValueOfstringstring (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons5__ArrayOfKeyValueOfstringstring(struct soap*, struct ns5__ArrayOfKeyValueOfstringstring *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons5__ArrayOfKeyValueOfstringstring(struct soap*, struct ns5__ArrayOfKeyValueOfstringstring *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons5__ArrayOfKeyValueOfstringstring(struct soap*, const char *, int, struct ns5__ArrayOfKeyValueOfstringstring *const*, const char *);
SOAP_FMAC3 struct ns5__ArrayOfKeyValueOfstringstring ** SOAP_FMAC4 soap_get_PointerTons5__ArrayOfKeyValueOfstringstring(struct soap*, struct ns5__ArrayOfKeyValueOfstringstring **, const char*, const char*);
SOAP_FMAC3 struct ns5__ArrayOfKeyValueOfstringstring ** SOAP_FMAC4 soap_in_PointerTons5__ArrayOfKeyValueOfstringstring(struct soap*, const char*, struct ns5__ArrayOfKeyValueOfstringstring **, const char*);

#ifndef SOAP_TYPE_PointerTons5__ArrayOfstring
#define SOAP_TYPE_PointerTons5__ArrayOfstring (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons5__ArrayOfstring(struct soap*, struct ns5__ArrayOfstring *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons5__ArrayOfstring(struct soap*, struct ns5__ArrayOfstring *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons5__ArrayOfstring(struct soap*, const char *, int, struct ns5__ArrayOfstring *const*, const char *);
SOAP_FMAC3 struct ns5__ArrayOfstring ** SOAP_FMAC4 soap_get_PointerTons5__ArrayOfstring(struct soap*, struct ns5__ArrayOfstring **, const char*, const char*);
SOAP_FMAC3 struct ns5__ArrayOfstring ** SOAP_FMAC4 soap_in_PointerTons5__ArrayOfstring(struct soap*, const char*, struct ns5__ArrayOfstring **, const char*);

#ifndef SOAP_TYPE_PointerToxsd__boolean
#define SOAP_TYPE_PointerToxsd__boolean (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__boolean(struct soap*, enum xsd__boolean *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__boolean(struct soap*, enum xsd__boolean *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__boolean(struct soap*, const char *, int, enum xsd__boolean *const*, const char *);
SOAP_FMAC3 enum xsd__boolean ** SOAP_FMAC4 soap_get_PointerToxsd__boolean(struct soap*, enum xsd__boolean **, const char*, const char*);
SOAP_FMAC3 enum xsd__boolean ** SOAP_FMAC4 soap_in_PointerToxsd__boolean(struct soap*, const char*, enum xsd__boolean **, const char*);

#ifndef SOAP_TYPE_PointerTons4__EILCommand
#define SOAP_TYPE_PointerTons4__EILCommand (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons4__EILCommand(struct soap*, struct ns4__EILCommand *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons4__EILCommand(struct soap*, struct ns4__EILCommand *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons4__EILCommand(struct soap*, const char *, int, struct ns4__EILCommand *const*, const char *);
SOAP_FMAC3 struct ns4__EILCommand ** SOAP_FMAC4 soap_get_PointerTons4__EILCommand(struct soap*, struct ns4__EILCommand **, const char*, const char*);
SOAP_FMAC3 struct ns4__EILCommand ** SOAP_FMAC4 soap_in_PointerTons4__EILCommand(struct soap*, const char*, struct ns4__EILCommand **, const char*);

#ifndef SOAP_TYPE_PointerTons4__MachineContext
#define SOAP_TYPE_PointerTons4__MachineContext (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons4__MachineContext(struct soap*, struct ns4__MachineContext *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons4__MachineContext(struct soap*, struct ns4__MachineContext *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons4__MachineContext(struct soap*, const char *, int, struct ns4__MachineContext *const*, const char *);
SOAP_FMAC3 struct ns4__MachineContext ** SOAP_FMAC4 soap_get_PointerTons4__MachineContext(struct soap*, struct ns4__MachineContext **, const char*, const char*);
SOAP_FMAC3 struct ns4__MachineContext ** SOAP_FMAC4 soap_in_PointerTons4__MachineContext(struct soap*, const char*, struct ns4__MachineContext **, const char*);

#ifndef SOAP_TYPE_ns3__guid
#define SOAP_TYPE_ns3__guid (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__guid(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns3__guid(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__guid(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__guid(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_ns3__guid(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_ns3__guid(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_ns3__duration
#define SOAP_TYPE_ns3__duration (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__duration(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns3__duration(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__duration(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__duration(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_ns3__duration(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_ns3__duration(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__duration
#define SOAP_TYPE_xsd__duration (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__duration(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__duration(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__duration(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__duration(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__duration(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__duration(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__decimal
#define SOAP_TYPE_xsd__decimal (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__decimal(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__decimal(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__decimal(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__decimal(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__decimal(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__decimal(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_PointerTounsignedByte
#define SOAP_TYPE_PointerTounsignedByte (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTounsignedByte(struct soap*, unsigned char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTounsignedByte(struct soap*, unsigned char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTounsignedByte(struct soap*, const char *, int, unsigned char *const*, const char *);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_get_PointerTounsignedByte(struct soap*, unsigned char **, const char*, const char*);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_in_PointerTounsignedByte(struct soap*, const char*, unsigned char **, const char*);

#ifndef SOAP_TYPE_xsd__anyURI
#define SOAP_TYPE_xsd__anyURI (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__anyURI(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__anyURI(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__anyURI(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__anyURI(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__anyURI(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__anyURI(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__IDREF
#define SOAP_TYPE_xsd__IDREF (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__IDREF(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__IDREF(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__IDREF(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__IDREF(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__IDREF(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__IDREF(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__ID
#define SOAP_TYPE_xsd__ID (6)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__ID(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__ID(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__ID(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__ID(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__ID(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__ID(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
