#!/usr/bin/env sh

# Asset refresh script
# --------------------
# In many ways, this has to be a fire-and-forget operation. We cannot
# communicate failures back to the steward since the asset info script handled
# as an init (which is by design, and this is desired).
#
# However, this is not a problem. We have designed for possible failures in the
# assetHelper library utilized by the steward itself (see
# lib_nmsa/assetHelper.h and the associated documentation in html/ for more
# information).

# The asset info script
ASSETINFO_SCRIPT="/etc/init.d/assetinfo"

# Command to refresh it
ASSETINFO_REFRESH="${ASSETINFO_SCRIPT} start"

# The asset info XML file itself
ASSETINFO_XML="/opt/intel/assetinfo"

# The steward init script
STEWARD_INIT="/etc/init.d/eil_steward.sh"

# First verify that the file exists
if [ -f "${ASSETINFO_SCRIPT}" ]; then
    # Alright, refresh it
    ${ASSETINFO_REFRESH}
    # Next, check to see if we have an assetinfo file after that operation
    if [ -f "${ASSETINFO_XML}" ]; then
    fi
fi

# vim:set ai et sts=4 sw=4 tw=80:
