#!/usr/bin/env sh

# Client update wrapper script
# ----------------------------
# Wraps the functionality found in the update pumper elsewhere

EIL_VERSION=$(cat ${LIB_DIR}/VERSION)

# Load our libraries
. /opt/intel/eil/clientagent/lib/helper.sh
. /opt/intel/eil/clientagent/lib/globals.sh

# The client agent bootstrapper
BOOTSTRAP_COMMAND="/opt/intel/eil/clientagent/tools/clientagent-bootstrap.sh"

trace "Update requested!"
trace "Current version is '${EIL_VERSION}'"

if [ -f "${BOOTSTRAP_COMMAND}" ]; then
    trace "Updating..."
    $BOOTSTRAP_COMMAND > /dev/null 2>&1
else
    trace_error "-----"
    trace_error "Client agent bootstrap command not found! Unrecoverable error during update request!"
    trace_error "Verify that the client agent is installed correctly, if not, a manual reinstall might be necessary!"
fi

# vim:set ai et sts=4 sw=4 tw=80:
