#!/usr/bin/env sh

# TCP diagnostic tool for the client agent (full version)

# This tool is to be called when the steward has detected a TCP error from a
# SOAP connection (e.g., it has tried to connect to CCMS, and a general TCP
# error was the result). This tool well determine what the problem was, and try
# to fix it.

# Load our libraries
. /opt/intel/eil/clientagent/lib/helper.sh
. /opt/intel/eil/clientagent/lib/globals.sh

HOST_IP=$(get_system_ip)

# vim:set ai et sts=4 sw=4 tw=80:
